### ISSUE TITLE
invalid syntax?

### ISSUE THREAD

**Issue by DWCastillo** [henrybetts/ableton-retime#1]
Hi,
Let me start by saying this script is EXACTLY what I've been missing from Ableton. 

I am barely python-literate, so pardon the fact my issue may be due to inexperience:

I have copied the py file into an Ableton project folder (so it's in same folder as .als file I want to edit), and opened the py file in Python (I have version 3.6). In Terminal, and am entering the following:
`[computername]:200525_jnana Project davidcastillo$ python ableton_retime.py --current-bpm 120 --target-bpm 68 200525_02_easyrider_untimed.als 200525_easyrider_timed.als`

and am getting the following error:

```
  File "ableton_retime.py", line 6
    def ableton_retime(*, source_file, target_file, current_bpm, target_bpm):
                        ^
SyntaxError: invalid syntax
```

Am I doing it right? Any help is hugely appreciated!

**Comment by henrybetts** [comment]
Hi @DWCastillo,

It looks like you probably are running it with python 2. You can check this by running:
`python --version`

It will depend on how you've installed the newer python version, but you will probably be able to run it like so:
`python3 ableton_retime.py ...`

At some point, I'll have a look at making the script backwards compatible, as I think MacOS still ships with python 2 by default.
