### ISSUE TITLE
BPM could be only INT, need to be FLOAT

### ISSUE THREAD

**Issue by patryk-siewiera** [henrybetts/ableton-retime#2]
Hey, 
I by mistake create my project in 4/4 in 80BPM, but I made the whole project around the loop 6/8.

So to correct it I should multiply by 133%.

80 * 133% = 106.40 BPM

Right now I could only type whole numbers. 

ps. this is an awesome tool, love from Poland ;)

**Comment by henrybetts** [comment]
Ah yes, I see the problem. https://github.com/henrybetts/ableton-retime/commit/e5fbd47be0f7954145550d1b600cd767c90c8192 should fix it.

I hadn't considered differences in time signature, but I suppose it should still work, and your value of 133% seems correct to me.

Thanks!

**Comment by patryk-siewiera** [comment]
that's great, thank you!
