### ISSUE TITLE
Ableton 10 incompatibility?

### ISSUE THREAD

**Issue by ijhicks** [henrybetts/ableton-retime#3]
Hi I just attempted to run this script with ableton and received an error:
`python3 ableton_retime.py --current-bpm 123 --target-bpm 106 201223_virus badself.als virus_test.als
usage: ableton_retime.py [-h] --current-bpm CURRENT_BPM --target-bpm
                         TARGET_BPM
                         source_file target_file
ableton_retime.py: error: unrecognized arguments: virus_test.als`

I'm wondering if 10 removed the ability to create a new project w python?

**Comment by henrybetts** [comment]
Hi, it looks like you have a space in your filename, so the script is picking up an extra argument. You should be able to wrap the filename in quotes, like so:

`python3 ableton_retime.py --current-bpm 123 --target-bpm 106 "201223_virus badself.als" virus_test.als`

Henry

**Comment by ijhicks** [comment]
ah yes, that worked! thank you! and thanks for creating this script, SUPER
helpful!
