### ISSUE TITLE
Ableton Live 11 / python 3.9

### ISSUE THREAD

**Issue by Benrubenru** [henrybetts/ableton-retime#4]
Hi Henry,

Thanks for making this script.
I would love to use it, but I don't have any experience with Python.
I installed Python 3.9, and I'm running Live 11.

I tried many variations, but I keep on getting invalid syntax messages when I try to run the following in Terminal:

python3 --ableton_retime.py --current-bpm120 --target-bpm145 oldtiming.als newtiming.als

```
>>> python3 --ableton_retime.py --current-bpm120 --target-bpm145 oldtiming.als newtiming.als
  File "<stdin>", line 1
    python3 --ableton_retime.py --current-bpm120 --target-bpm145 oldtiming.als newtiming.als
                                                                 ^
SyntaxError: invalid syntax
```

Is there anything else I could try? Any help would be greatly appreciated!

**Comment by henrybetts** [comment]
Hey,

Your syntax doesn't look quite right. Have you tried;
`python3 ableton_retime.py --current-bpm 120 --target-bpm 145 oldtiming.als newtiming.als`

I haven't tried it with Live 11, so it will be interesting to see whether it still works.
Let me know!

**Comment by Benrubenru** [comment]
Thanks a lot, it works perfectly for Live 11!

Cheers!
